@startuml
title 基于GitHub的实验管理平台--查看成绩用例的顺序图
actor user
user ->users:查看成绩
alt 如果user是老师
	users -> teachers
	teachers --> term:选择学期
	term --> course:选择课程
	course --> tests:每个实验
	tests --> user:返回每个同学的成绩
else 如果users是students
    user --> users:查看成绩
     users -->students
     students -->term:选择学期
     term --> course:选择课程
     	course --> tests:每个实验
     	tests --> user:返回该同学的成绩
end
@enduml