@startuml
title 基于GitHub的实验管理平台--选课用例的顺序图
actor user
user ->users:选课
alt 如果user是老师
	users --> term:选择学期
	term --> course:选择课程
	course --> users:更新课程
else 如果users是students
    user --> users
     users -->term:选择学期
     term --> teachers:选择老师
     	teachers --> course:选择课程
     	course --> users:更新学生课程
end
@enduml